if(EXISTS "/usr/src/projects/build_coverage/crud_handler_factory_test[1]_tests.cmake")
  include("/usr/src/projects/build_coverage/crud_handler_factory_test[1]_tests.cmake")
else()
  add_test(crud_handler_factory_test_NOT_BUILT crud_handler_factory_test_NOT_BUILT)
endif()
