if(EXISTS "/usr/src/projects/build_coverage/echo_handler_factory_test[1]_tests.cmake")
  include("/usr/src/projects/build_coverage/echo_handler_factory_test[1]_tests.cmake")
else()
  add_test(echo_handler_factory_test_NOT_BUILT echo_handler_factory_test_NOT_BUILT)
endif()
