if(EXISTS "/usr/src/projects/build_coverage/server_lib_test[1]_tests.cmake")
  include("/usr/src/projects/build_coverage/server_lib_test[1]_tests.cmake")
else()
  add_test(server_lib_test_NOT_BUILT server_lib_test_NOT_BUILT)
endif()
